package mocks

import "github.com/stretchr/testify/mock"

import "github.com/t11e/go-discoveryclient"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Query provides a mock function with given fields: dataset, query
func (_m *Client) Query(dataset string, query *discoveryclient.Query) (*discoveryclient.Results, error) {
	ret := _m.Called(dataset, query)

	var r0 *discoveryclient.Results
	if rf, ok := ret.Get(0).(func(string, *discoveryclient.Query) *discoveryclient.Results); ok {
		r0 = rf(dataset, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*discoveryclient.Results)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *discoveryclient.Query) error); ok {
		r1 = rf(dataset, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
